### ISSUE TITLE
will it block when I make a rpc request on my client server?

### ISSUE THREAD

**Issue by Friday21** [Thriftpy/thriftpy2#112]
I use flask providing web api, above flask, I use gunicorn <gevent workder> to patch all block I/O such as pymongo and requests, but I think it will block on rpc client request, because rpc use tcp to communicate, and gunicorn don't patch it. so, how can I make the client request not blocking?

我用flask框架来做服务端， 项目启动的时候用gunicorn的gevent的worker模式， 据我所知， gevent会把Python标准库以及常用的pymongo等数据库请求以及requests等库patch成非阻塞的，这样我的服务就可以有很大的并发能力，但我们现在用了thrift rpc之后， 我怀疑在做rpc请求时（本服务向另一个微服务请求）， I/O 会阻塞掉， 请问有什么好方法来解决呢？ 请求调用改成asyncio能解决这个问题吗（我不确定thriftpy里边实际的tcp过程是否会继续阻塞的）？

**Comment by ethe** [comment]
If you use the monkey path of Gevent, thriftpy would not block the process, please make sure that thriftpy is under monkey path. And please do not use asyncio and gevent together, choose one of them to be your project's concurrency model.

**Comment by Friday21** [comment]
> If you use the monkey patch of Gevent, thriftpy would not block the process, please make sure that thriftpy is under monkey path. And please do not use asyncio and gevent together, choose one of them to be your project's concurrency model.

Thanks, your answer makes things easier.

**Comment by aisk** [comment]
You must ensure monkey patch is done before any other package's import. It works well under my project.

**Comment by Friday21** [comment]
> You must ensure monkey patch is done before any other package's import. It works well under my project.

Yes, I do. I use gunicorn (gevent worker mode) start my server,  and gunicorn will do the patch before my project init. 

```
class GeventWorker(AsyncWorker):
    def patch(self):
        monkey.patch_all()
        ...

    def init_process(self):
        self.patch()
        hub.reinit()
        super(GeventWorker, self).init_process()  # init my project 
```

**Comment by ethe** [comment]
Closed, would reopen if there are any feedbacks.
