### ISSUE TITLE
os.path.samfile patch craches shutil.copy2 under python 2.7.15

### ISSUE THREAD

**Issue by Josef-A** [Thriftpy/thriftpy2#117]
The patch https://github.com/Thriftpy/thriftpy/pull/172 changes the behavior of os.path.
The function os.path.samefile is not available for Python 2 under windows. The patch adds that function. Unfortunately it doesn't work as expected.

I have some code that copies one file to another:

``` python
src = u'D:\\tmp\\source.txt'
dst = u'D:\\tmp\\destination.txt'
shutil.copy2(src, dst)
```

If the files are identical it will crash.

My workaround is:
``` python
if sys.version_info.major == 2 and hasattr(os.path, 'samefile'):
    # Run with hack
    backupfcn = os.path.samefile
    del os.path.samefile
    shutil.copy2(src, src)
    os.path.samefile = backupfcn
else:
    shutil.copy2(src, src)
```

I can live with it. I am in the process of migrating to Python 3, and then this patch will not be used if I understand it correct.

I just wanted to indicate that the patch has impacts that may not have been intended

Regards
     Josef

**Comment by ethe** [comment]
Hi @Josef-A,

I am glad to be noticed, I think this information is useful to help others which still uses Python 2 diagnoses the issue. However, I think we would not fix it in the future because Python 2 has already deprecated. I will keep this issue for a while to remind others. Thank you.

Regards
Gwo Tzu-hsing

**Comment by Josef-A** [comment]
Hi @ethe, 
Yes, that is exactly why I opened the issue. Absolutely ok that it will be closed later on. It will still be searchable.
   /Josef

**Comment by ethe** [comment]
Closed.
