### ISSUE TITLE
client can not connect to remote server with the pingpong demo

### ISSUE THREAD

**Issue by xinglinyin** [Thriftpy/thriftpy2#12]
@ethe  
when  I run the demo such as, raise exception can not conect demo server.
it ok for client and server run the same machine
but not worked for two different machine.   
Thank you very much for any help.
![image](https://user-images.githubusercontent.com/26497032/47264060-efa52180-d540-11e8-90ed-f90055fca311.png)

**Comment by chris4dd** [comment]
@xinglinyin 
Hi is this fixed? I face the same issue as you, would you please shed some light on it?
