### ISSUE TITLE
why it happen? thanks!

### ISSUE THREAD

**Issue by dmax678** [Thriftpy/thriftpy2#120]
from thriftpy2.protocol import TCyBinaryProtocolFactory
ImportError: cannot import name 'TCyBinaryProtocolFactory' from 'thriftpy2.protocol'

**Comment by ethe** [comment]
Try to install Cython first.

**Comment by dmax678** [comment]
> Try to install Cython first.
emm..i have already install cython,but..it still have that error

**Comment by ethe** [comment]
Please make sure that Cython is installed before Thriftpy.
