### ISSUE TITLE
How to close a server?

### ISSUE THREAD

**Issue by danieljfarrell** [Thriftpy/thriftpy2#127]
I want to start and stop a thriftpy2 service from inside a running desktop application. However, calling `close` on the server does not terminate it’s thread and the application hangs.

For example,

```python
def start_button_clicked(self):
    self.server = make_server(...)
    self.thd = threading.Thread(target=server.serve)

def stop_button_clicked(self):
    self.server.close()
    self.thd.join() # <— hangs 
    self.server = None
    self.thd = None
```

Maybe I am doing something wrong?

I’m using Python 3.6.9 and thriftpy2 0.4.10 on Windows 10.

**Comment by danieljfarrell** [comment]
```
  File "/Users/daniel/.pyenv/versions/testing_thriftpy2/lib/python3.7/site-packages/thriftpy2/transport/socket.py", line 219, in accept
    client, _ = self.sock.accept()
```
It seems the thread is blocking here, waiting for the socket to accept something.

**Comment by danieljfarrell** [comment]
I came across this similar issue on the deprecated project page, https://github.com/Thriftpy/thriftpy/issues/295. If I kill the transport and the socket I can get the thread to exit!

```python
def stop_button_clicked(self):
    server.close()
    server.trans.close()  # <-- kill this
    server.trans.sock.close()  # <-- kill this
    self.thd.join()  # <-- now joins
    self.server = None
    self.thd = None
```

What would you like to do? Shall I prepare a pull request?

**Comment by ethe** [comment]
Hanging in `accept` means there is still at least one socket that is completed and waiting for transporting from the client, close it right now would make the client raise an exception.

**Comment by aisk** [comment]
Another way to solve this is you can set a timeout on server socket like this: `server.trans.sock.settimeout(1)`. And the accept should in a dead loop to call this eventually, and with a flag to check should it closed.

**Comment by danieljfarrell** [comment]
Thanks for the comments both! So there must be a client connection still open, otherwise the server should close? 

Setting the timeout on the socket is a much better way to go.
