### ISSUE TITLE
Unable to use thriftpy2 on AWS lambda

### ISSUE THREAD

**Issue by liamschn** [Thriftpy/thriftpy2#134]
[ERROR] Runtime.ImportModuleError: Unable to import module '[modulename]': cannot import name 'TCyBinaryProtocol' from 'thriftpy2.protocol.cybin' (unknown location)

[modulename] is the name of the module I am creating.

I have already tried what is listed in [Import issue on AWS Lambda #36](https://github.com/Thriftpy/thriftpy2/issues/36)
Last comment in the above issue mentions "...C extensions require GCC or LLVM for installation, try to install it with GCC on Linux...", however, AWS lambda does not allow you to "install it with GCC on linux"...but that would have been accomplished with the fact that I set all of this up on an AWS linux instance and copied it from there (after confirming that it worked)
The code runs without problems at all on a regular AWS linux instance, but when uploaded to AWS lambda, it throws the error above.

**Comment by liamschn** [comment]
Fixed by using python 3.7 instead of python 3.8 runtime in AWS lambda.  Must be something with python 3.8?

**Comment by ethe** [comment]
Could you please provide more info about it?
