### ISSUE TITLE
mixed up binary and string types

### ISSUE THREAD

**Issue by vitrun** [Thriftpy/thriftpy2#136]
why does thriftpy2 treat `binary` as `string`?

in [thrift.py](https://github.com/Thriftpy/thriftpy2/blob/90cbc37191364a82ec8a847c5c578024defcca83/thriftpy2/thrift.py#L88):

```python
    STRING = 11
    UTF7 = 11
    BINARY = 11  # This here just for parsing. For all purposes, it's a string
```

this may cause inconvenience when sending files, images, etc.

**Comment by ethe** [comment]
There is no difference between string and binaries in Python 2, so it is not be considered before.

**Comment by ethe** [comment]
Close via #139
