### ISSUE TITLE
how to use multi server with its own port

### ISSUE THREAD

**Issue by better629** [Thriftpy/thriftpy2#14]
Hi ,
     I want to know how to use multi server with its own port in a program. For example, PingPing.ping use 127.0.0.1:80；PingDong.dong use 127.0.0.1:8080 as server address.
     It seems that TThreadedServer supports multi server with same port in a program.

Thx!

**Comment by ethe** [comment]
Just use [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) to load more than one server. I think it's not a problem about Thriftpy.

**Comment by wooparadog** [comment]
Actually, it's better practice to start independent processes for different services(in python anyway..)
