### ISSUE TITLE
Invalid HTTP URI format in http.py

### ISSUE THREAD

**Issue by JonnoFTW** [Thriftpy/thriftpy2#140]
https://github.com/Thriftpy/thriftpy2/blob/a8b7873078a6f38a2f052964d439ab888e32fcf4/thriftpy2/http.py#L63

It's missing the `/`  between the port and the path and should be:

```python
HTTP_URI = '{scheme}://{host}:{port}/{path}'
```

This only occurs if you leave out the `/` in your path variable.

**Comment by ethe** [comment]
Thank you for reporting, yes it is a bug.
