### ISSUE TITLE
从thrift转到thriftpy时，请求的编码变了？

### ISSUE THREAD

**Issue by djk454772303** [Thriftpy/thriftpy2#142]
在将服务从thrift迁移到thriftpy时，请求里的字符编码变了。在thriftpy里一些字段变为了unicode编码，看着像是对原始的字符串多做了一次utf8的decode

**Comment by aisk** [comment]
thriftpy2 will call `.decode('utf-8')` for string or binary type fields. You can set `decode_response` to `False` on your protocol factory to disable this behavior.

**Comment by djk454772303** [comment]
> thriftpy2 will call `.decode('utf-8')` for string or binary type fields. You can set `decode_response` to `False` on your protocol factory to disable this behavior.

thx. 问题解决了~
