### ISSUE TITLE
if I update thrift server to thriftpy2 ,should I update the client?

### ISSUE THREAD

**Issue by djk454772303** [Thriftpy/thriftpy2#143]
my client is coded in C.

**Comment by ethe** [comment]
No, you do not have to.

**Comment by ethe** [comment]
Please use the protocol and transport which thriftpy2 supports.

**Comment by djk454772303** [comment]
> No, you do not have to.

But when I do this, my c client come to exception.  The server can receive the request and return normal ,but the C client cannot receive the response.

**Comment by djk454772303** [comment]
> Please use the protocol and transport which thriftpy2 supports.

This means I should update my C client include file?

**Comment by djk454772303** [comment]
> Please use the protocol and transport which thriftpy2 supports.

The protocol I used is TBinaryProtocol and The transport I used is TBufferedTransport.

**Comment by ethe** [comment]
Keep IDL, protocol and transport are the same in both server and client.

**Comment by djk454772303** [comment]
> Keep IDL, protocol and transport are the same in both server and client.

how can i use the type defined in IDL in my python file?

**Comment by djk454772303** [comment]
my server python main code :
iprot_factory_m = TBinaryProtocolFactory(strict_read=False, decode_response=False)
oprot_factory_m = TBinaryProtocolFactory(strict_write=False, decode_response=False)
server = TSimpleServer(processor, server_socket, iprot_factory= iprot_factory_m, oprot_factory=oprot_factory_m)

my client C main code:
boost::shared_ptr<transport::TSocket> socket(new transport::TSocket(serv_now.ip, serv_now.port));
boost::shared_ptr<transport::TTransport> transport(new transport::TBufferedTransport(socket));
boost::shared_ptr<protocol::TProtocol> protocol(new protocol::TBinaryProtocol(transport));
DaClient client(protocol);
..

I think the server and the client use the same protocol and transport.

The IDL file. client code used the generated by thrift,  and the server python code directly used the IDL file, and the IDL file is the same.

**Comment by JonnoFTW** [comment]
@djk454772303 what does your .thrift file look like?

**Comment by ethe** [comment]
Re-open if more info is provided.
