### ISSUE TITLE
about log request parameters

### ISSUE THREAD

**Issue by better629** [Thriftpy/thriftpy2#17]
Hi,
    How to get the request parameters for logging, is there any example to check.
    Which I mean define a method as below:
          string ping(1:i32 a, 2:i32 b)
    can I catch the parameters of ping(1, 2, 3). It seems that it only print (1,2)

Thx.

**Comment by ethe** [comment]
Thriftpy does not accept parameter which is not defined in IDL, cause Thriftpy does not know how to deserialize it.
