### ISSUE TITLE
Why dead include checking on current stack？

### ISSUE THREAD

**Issue by iyaozhen** [Thriftpy/thriftpy2#186]
My service maybe special, not rpc client or server.
I am a http server, just load thrift file runtime, and return service meta.
So, multi request has same thrift file path.

```
Dead including on /path/xxx.thrift
```
Is mean `thriftpy2.load` not thread safety ?
https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/parser/parser.py#L547

python3 -V
Python 3.7.2

**Comment by aisk** [comment]
Yes, `thriftpy2.load` is not thread safe, this is a known issue.

**Comment by iyaozhen** [comment]
@aisk 感谢回复，“Python之父“。莫愁前路无知己，天下谁人不识君。🌹
