### ISSUE TITLE
What if I remove the `while True` loop in TThreadedServer?

### ISSUE THREAD

**Issue by wangheda** [Thriftpy/thriftpy2#189]
In TThreadedServer, what if I remove the `while True` loop and process just once? The while loop seems to prevent the thread from ending and keeps memory usage growing. 
 
       def handle(self, client):
                itrans = self.itrans_factory.get_transport(client)
                otrans = self.otrans_factory.get_transport(client)
                iprot = self.iprot_factory.get_protocol(itrans)
                oprot = self.oprot_factory.get_protocol(otrans)
                try:
                    # while True:
                        self.processor.process(iprot, oprot)
                except TTransportException:
                    pass
                except Exception as x:
                    logger.exception(x)

**Comment by aisk** [comment]
I think the server will close connect after handle one request if you remove the look.
