### ISSUE TITLE
correspondence between thriftpy2 and thrift versions

### ISSUE THREAD

**Issue by yiqijiu** [Thriftpy/thriftpy2#209]
"As the title suggests, I want to know the relationship between thriftpy2 and thrift versions. Currently, when I use HappyBase to access HBase, an error is reported: TTransportException(type=4,message='Tsocket read 0 bytes'), and the thriftpy2 version is 0.4.16, which is the latest version I am using. Then I found that HBase's thrift uses version 0.14.1. Which version of thriftpy2 should I use?"
thx

**Comment by ethe** [comment]
You should always use the latest version of thriftpy2, if you could always reproduce this issue, please post a minimal case here, I would like to test it later.

**Comment by yiqijiu** [comment]
```python
import happybase

# Create a connection to the HBase using HappyBase client
connection = happybase.Connection('localhost', port=9090)

# Create a table named 'mytable'
table_name = 'mytable'
column_family = 'cf'
connection.create_table(
    table_name,
    {column_family: dict()},
)

# Get the table object for 'mytable'
table = connection.table(table_name)

# Insert a row of data into 'mytable'
table.put(b'row1', {b'cf:col1': b'value1', b'cf:col2': b'value2'})

# Get a row of data from 'mytable'
row = table.row(b'row1')
print(row[b'cf:col1'])  # output: b'value1'

# Close the connection
connection.close()



```

**Comment by yiqijiu** [comment]
Thank you, I have resolved the issue, it was my mistake. The solution was to replace the hbase.thrift of HappyBase with the one in the hbase cluster, and ensure that the connection protocol and cluster configuration are consistent. Sorry for bothering you for so long.

**Comment by aisk** [comment]
``TTransportException(type=4,message='Tsocket` read 0 bytes')` means the server closed the TCP connection without sending anything. This will happened when the server can't under standing the request protocol (like it's not a thrift server, or have different protocol / transport config), or just got an error when processing the request and the IDL for this request have no exception assumed. 

Or, this is an "502" in HTTP protocol.
