### ISSUE TITLE
load, load_module behaviour 

### ISSUE THREAD

**Issue by Niccolum** [Thriftpy/thriftpy2#217]
Hello!

Is it possible to generate python model, based on .thrift file, like official library can do?

I explain. I have a lot of thrift models in remote repository, but i need only one. Of course, I can load by http, but it can changed. I need to "freeze" my thrift requirements for my application, and "update" if need. Not only "real-time" update, like now, with cache.

Is it possible? Or how do you recommend to do?

**Comment by aisk** [comment]
This is not supported currently.

**Comment by Niccolum** [comment]
Is this in the plans? Do you know?

**Comment by aisk** [comment]
No, personally I recommend copy the thrift and assume that the `.thirift` files were generated python files.
