### ISSUE TITLE
Cython issue still occurring because the fix wasn't published 

### ISSUE THREAD

**Issue by ofiry-tm** [Thriftpy/thriftpy2#224]
I get the Cython issue in the latest published version 0.4.16:
```
Error compiling Cython file:
------------------------------------------------------------
...

    cdef int grow(self, int min_size):
        if min_size <= self.buf_size:
            return 0

        cdef int multiples = min_size / self.buf_size
                                      ^
------------------------------------------------------------

thriftpy2/transport/cybase.pyx:90:38: Cannot assign type 'double' to 'int'
```

it seemed to be fixed now on master branch:
https://github.com/Thriftpy/thriftpy2/commit/202ed5ef7b91399b86f8b3b76108a14612b38dbc

but it was never published as a new version,
can you please publish a new version ?

**Comment by ofiry-tm** [comment]
@ethe @aisk please help

**Comment by ethe** [comment]
v0.14.7 has released, thanks

**Comment by ofiry-tm** [comment]
@ethe I see that you merged the version change, but the latetst release version is still v0.14.6

**Comment by aisk** [comment]
The latest version is `v0.14.7` https://pypi.org/project/thriftpy2/#history .
