### ISSUE TITLE
import hook does not work with Python3.12

### ISSUE THREAD

**Issue by aisk** [Thriftpy/thriftpy2#229]
According to [sys.meta_path](https://docs.python.org/3/library/sys.html#sys.meta_path)'s document:

> Changed in version 3.4: [Module specs](https://docs.python.org/3/glossary.html#term-module-spec) were introduced in Python 3.4, by [PEP 451](https://peps.python.org/pep-0451/). Earlier versions of Python looked for a method called find_module(). This is still called as a fallback if a [meta_path](https://docs.python.org/3/library/sys.html#sys.meta_path) entry doesn’t have a [find_spec()](https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder.find_spec) method.

thriftpy is using `find_module` and this is removed in https://github.com/python/cpython/issues/98040, so import hook does not work in Python 3.12

**Comment by ookice** [comment]
update Dependencies or review PEPs?
