### ISSUE TITLE
What's the difference between v1 and v2?

### ISSUE THREAD

**Issue by torpedoallen** [Thriftpy/thriftpy2#28]
Can you provide some background information about the migration? We used the thriftpy v1 in production environment perfectly and someday my colleague told me v2 had come out. We prefer to do the migration after having enough background knowledge.

Thank in advance.

**Comment by ethe** [comment]
Thriftpy has not had any maintainers in a long time, even we can not find a guy which is able to upload a new version to PyPi. So we make thriftpy2 and rebuild all things: CI, docs, pypi, etc.

Thriftpy2 is fully compatible with thriftpy, and it fixed some bug in thriftpy, and supports asyncio in Python3.x which is not be supported in thriftpy, thats's all.  you can check all changes [here](https://github.com/Thriftpy/thriftpy2/blob/master/CHANGES.rst).

**Comment by torpedoallen** [comment]
Thanks, I appreciate it.
