### ISSUE TITLE
Import issue on AWS Lambda

### ISSUE THREAD

**Issue by springcoil** [Thriftpy/thriftpy2#36]
I'm trying to get Thriftpy2 to work with AWS Lambda. AWS Lambda depends on an AWS Linux which I think is based on RHEL/centos. 
https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html 

I get the following error:
```(aws) bash-4.2# python lambda_func.py
Traceback (most recent call last):
  File "lambda_func.py", line 3, in <module>
    from thriftpy2.protocol import TCyBinaryProtocolFactory
  File "/var/task/thriftpy2/protocol/__init__.py", line 14, in <module>
    from .cybin import TCyBinaryProtocol, TCyBinaryProtocolFactory
ModuleNotFoundError: No module named 'thriftpy2.protocol.cybin'```

**Comment by ethe** [comment]
Try to reinstall thriftpy with `pip install cython thriftpy2`

**Comment by ethe** [comment]
Closed, will reopen with more information.

**Comment by gautacharya** [comment]
Updates on this? Running into the same issue.

**Comment by ethe** [comment]
@gautacharya Try to use `pip install cython thriftpy2`

**Comment by gautacharya** [comment]
Is that all that needs to be done? Just installing cython along with ThriftPy2?

I am actually using HappyBase, which relies on ThriftPy2. But the problem is in ThriftPy2.

**Comment by ethe** [comment]
@gautacharya Please run `pip freeze` to print the version of thriftpy2 on your machine and tell me which OS you used.

**Comment by ethe** [comment]
@gautacharya thriftpy2 depends on some C extensions to boost the parser, that is the reason for thriftpy2 is faster than apache thrift, Cython extensions require GCC or LLVM for installation, try to install it with GCC on Linux.
