### ISSUE TITLE
Installing thriftpy2 on pypy breaks installing it on CPython

### ISSUE THREAD

**Issue by drolando** [Thriftpy/thriftpy2#40]
If you run `pip install thriftpy2` in  a pypy virtualenv, pip generates a `thriftpy2-0.4.1-py2.py3-none-any.whl` wheel which won't work in CPython. `pip` also saves these wheels in your home folder cache, which means that if you try to install it in any other virtualenv afterwards it'll just use that cached wheel.

If you now install it in a CPython virtualenv and try to import `from thriftpy2.protocol.binary import read_list_begin` you'll get an error like `ModuleNotFoundError: No module named 'thriftpy2.protocol.cybin'`.

From what I understand, when we're running in pypy we don't compile some modules with cython. Which is why it generates a universal wheel. However when running in CPython the code somehow understands that you should have compiled those modules, so it tries to import the .so files. And fails since the wheel was built in pypy.

This is very annoying since I have to either always specify `--no-binary thriftpy2` in every pip install or wipe my local cache every time I run the tests.

I'm not sure what the best solution is here, but if we made the code resistant to those modules being missing that'd already help.

--------------

To reproduce just create a Dockerfile with this content:
```Dockerfile
FROM ubuntu:bionic

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    pypy \
    python3-dev \
    virtualenv

RUN virtualenv -p pypy venv_pypy
RUN venv_pypy/bin/pip install -v thriftpy2
RUN venv_pypy/bin/python -c 'from thriftpy2.protocol.binary import read_list_begin'

RUN virtualenv -p python3 venv_py3
RUN venv_py3/bin/pip install -v thriftpy2
RUN venv_py3/bin/python -c 'from thriftpy2.protocol.binary import read_list_begin'
```
and then run `docker build .`

**Comment by drolando** [comment]
Forgot to mention: this is not a new issue, thriftpy has the exact same problem.

**Comment by ethe** [comment]
Use `RUN venv_py3/bin/pip install --no-cache-dir thriftpy2` instead.

**Comment by drolando** [comment]
Well yeah, but that's another workaround like using `--no-binary thriftpy2`. It'd be nice that the library just worked like any other library

**Comment by drolando** [comment]
I think it'd be enough that instead of doing `if PYPY` in https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/protocol/__init__.py we just did
```python
try:
    from .cybin import TCyBinaryProtocol, TCyBinaryProtocolFactory
    TBinaryProtocol = TCyBinaryProtocol  # noqa
    TBinaryProtocolFactory = TCyBinaryProtocolFactory  # noqa
except ImportError:
    # disable cython binary protocol for PYPY since it's slower.
    TCyBinaryProtocol = TBinaryProtocol
    TCyBinaryProtocolFactory = TBinaryProtocolFactory
```
which is also more in line with python's guidelines to check for behavior rather than having specific py2/3 or pypy if/else

**Comment by drolando** [comment]
same in https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/transport/__init__.py

**Comment by ethe** [comment]
There are no more speed up your service with Cython if you used `--no-binary`, in a similar way, `try import ... except ...` also makes user confused, there is no clearly way to know which protocol is working  currently. So I think it is not a good solution to catch import exception silently.

**Comment by ethe** [comment]
Closed and would open in the future if get more feedback.
