### ISSUE TITLE
Add URL parsing to make_client/client_context

### ISSUE THREAD

**Issue by dmulter** [Thriftpy/thriftpy2#48]
Currently you must pass in `host`, `scheme`, and `path` when using the `HTTPClient`. It would be a nice feature to take a `url` parameter, and have the client method use `urllib.parse` to extract out these values for the caller.

**Comment by ethe** [comment]
There is no standard DSN of Apache Thrift, but I think we can simply define it like `thrift://host:port`

**Comment by Swixx** [comment]
@dmulter is the idea to have url as a kwarg?
@ethe does that mean we would have to change the signature to make `host` and `port` optional, but enforce one or the other?

**Comment by ethe** [comment]
@Swixx I will not break down anything. URL will be an optional argument, you can still use host and port in the future.

**Comment by Swixx** [comment]
@ethe I do not want to break anything either. I want to make a PR, but want to be sure that we get the best interface to the function possible. Currently, the signature is 
`make_client(service, host, port, path='', scheme='http',
                proto_factory=TBinaryProtocolFactory(),
                trans_factory=TBufferedTransportFactory(),
                ssl_context_factory=None,
                timeout=DEFAULT_HTTP_CLIENT_TIMEOUT_MS):`

If we put an optional kwarg for `url`, that essentially makes host and port unnecessary, but they are currently required positional arguments, so a call such as
`make_client(pingpong.PingService, url='https://example.com:443', ssl_context_factory=ssl_context_factory)`
would be invalid, even though we could extract out the necessary information.

What would your idea be for how to call the function if we made `url` a kwarg?

We could overload the function, but I don't know if that is necessary.

**Comment by ethe** [comment]
@Swixx I think
```python
def make_client(service, host='', port='', path='', scheme='http', proto_factory=TBinaryProtocolFactory(), trans_factory=TBufferedTransportFactory(), ssl_context_factory=None, timeout=DEFAULT_HTTP_CLIENT_TIMEOUT_MS, url=''):
    pass
```
is a good solution. Make host and port optional and put the url end of the args will not break anything, user can still use `make_client(pingpong.PingService, '127.0.0.1', '5000')`, and also `make_client(pingpong.PingService, url='http://127.0.0.1:5000')`

**Comment by Swixx** [comment]
@ethe there is currently a `make_client` in `http.py`, `rpc.py`, `tornado.py`, and `contrib/aio/rpc.py`. Should all of these implement the new functionality?

Additionally, how should I make test cases? There is currently tests for `tornado` and `rpc` make client, done by implementing a `mk_client()` method. What is your preferred method of testing this?

**Comment by ethe** [comment]
Yeah I think you should implement another function for each package, the name of function may like `make_client_from_dsn` or something similar.

It is better to add test cases for this feature, be similar with `mk_client` is fine I think.

**Comment by Swixx** [comment]
Do you think that's a better interface than just putting another kwarg at the end of make_client?
I was playing around with it yesterday and didn't see the issue regarding *args and **kwargs. regarding *args, the same order will arise, and the **kwargs will only be affected if the client uses the new `url` kwarg.
Something like this:
```
def make_client(service, host='', port='', path='', scheme='http',
                proto_factory=TBinaryProtocolFactory(),
                trans_factory=TBufferedTransportFactory(),
                ssl_context_factory=None,
                timeout=DEFAULT_HTTP_CLIENT_TIMEOUT_MS, url=None):

    if url is not None:
        _url = urllib.parse.urlparse(url)
        host = _url.hostname or host
        port = _url.port or port
        path = _url.path or path
        scheme = _url.scheme or scheme
```

**Comment by ethe** [comment]
@Swixx Looks good to me 😄
