### ISSUE TITLE
是否可以增加多个idl文件相互 include 的使用代码示例呢？谢谢

### ISSUE THREAD

**Issue by zeyu203** [Thriftpy/thriftpy2#49]
是否可以增加多个idl文件相互 include 的使用代码示例呢？谢谢

**Comment by ethe** [comment]
See https://github.com/Thriftpy/thriftpy2/blob/master/tests/addressbook.thrift#L1 , if you get more problems, please describe it specifically.

**Comment by ethe** [comment]
See https://github.com/Thriftpy/thriftpy2/blob/master/tests/addressbook.thrift#L1 , if you get more problems, please describe it specifically.

**Comment by zeyu203** [comment]
多谢，建议可以放到 samples 目录，谢谢
