### ISSUE TITLE
thriftpy2/parser/parser.py raise an error

### ISSUE THREAD

**Issue by duyue9522** [Thriftpy/thriftpy2#50]
File "/data/www/envs/flask/lib/python2.7/site-packages/happybase/__init__.py", line 10, in <module>
    'Hbase_thrift')
  File "/data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/__init__.py", line 33, in load
    include_dir=include_dir)
  File "/data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/parser.py", line 545, in parse
    lexer = lex.lex()
  File "/data/www/envs/flask/lib/python2.7/site-packages/ply/lex.py", line 910, in lex
    raise SyntaxError("Can't build lexer")
SyntaxError: Can't build lexer

**Comment by duyue9522** [comment]
os: centos6

**Comment by duyue9522** [comment]
and:
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:168: No regular expression defined for rule 't_newline'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:173: No regular expression defined for rule 't_ignore_SILLYCOMM'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:178: No regular expression defined for rule 't_ignore_MULTICOMM'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:183: No regular expression defined for rule 't_ignore_DOCTEXT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:188: No regular expression defined for rule 't_ignore_UNIXCOMMENT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:192: No regular expression defined for rule 't_ignore_COMMENT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:196: No regular expression defined for rule 't_BOOLCONSTANT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:202: No regular expression defined for rule 't_DUBCONSTANT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:208: No regular expression defined for rule 't_HEXCONSTANT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:215: No regular expression defined for rule 't_INTCONSTANT'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:221: No regular expression defined for rule 't_LITERAL'
ERROR: /data/www/envs/flask/lib/python2.7/site-packages/thriftpy2/parser/lexer.py:252: No regular expression defined for rule 't_IDENTIFIER'

**Comment by ethe** [comment]
Please post a minimal sample here to reproduce your issue, thanks.

**Comment by duyue9522** [comment]
i start it by runserver success,
but i run it by uwsgi failed

**Comment by ethe** [comment]
Thriftpy does not support UWSGI, maybe you need https://github.com/Thriftpy/gunicorn_thrift
