### ISSUE TITLE
Service method named 'close' in thrift file seems to be incorrectly translated in client

### ISSUE THREAD

**Issue by flboudet** [Thriftpy/thriftpy2#52]
Hi,
I am implementing a Python client using thriftpy2 to a thrift C++ server.
One of the method from a service is called 'close'.
It seems that the thriftpy client fails to implement it correctly.

I have written a minimalist python script that reproduces the issue.
The script loads the following thrift file:
<pre>
service File {
    void close(1: i32 idfile, 2: string anything);
    void close2(1: i32 idfile, 2: string anything);
}
</pre>

It then prints the signature of the close and close2 methods, as loaded by the thriftpy client:
<pre>
#!/usr/bin/python3

import thriftpy2
from thriftpy2.rpc import client_context
from thriftpy2.rpc import make_client
from thriftpy2.protocol import (
    TBinaryProtocolFactory,
    TMultiplexedProtocolFactory
)

import inspect

file_thrift = thriftpy2.load("File.thrift", module_name="file_thrift")
binary_factory = TBinaryProtocolFactory()
client = make_client(file_thrift.File, '192.168.57.2', 9090,
                     proto_factory=binary_factory)

print("Signature of the close method:")
print(inspect.signature(client.close))
print("Signature of the close2 method:")
print(inspect.signature(client.close2))
</pre>

Here is the output I get:

<pre>
Signature of the close method:
()
Signature of the close2 method:
(*args, **kwargs)
</pre>

It seems that thriftpy has some conflict with the name 'close'.
Eventually, is there a way to aliase the thrift service method name? (I cannot change it in the server implementation)

Regards,
Florent
[thriftpy2_close_bug.zip](https://github.com/Thriftpy/thriftpy2/files/3177512/thriftpy2_close_bug.zip)

**Comment by ethe** [comment]
Thank you for your reporting, seems like `close` is a reserved method, I will think about how to work around it.

**Comment by ethe** [comment]
Hi, 0.4.3 released, now you can use `tclose` to call your `close` api, have a nice day.

**Comment by flboudet** [comment]
Thank you very much, it works perfectly! Have a nice day.
