### ISSUE TITLE
How to close socket connection when using make_client?

### ISSUE THREAD

**Issue by collinmazb** [Thriftpy/thriftpy2#59]
```
 import thriftpy2

 pingpong_thrift` = thriftpy2.load("pingpong.thrift", module_name="pingpong_thrift")

from thriftpy2.rpc import make_client

client = make_client(pingpong_thrift.PingPong, '127.0.0.1', 6000)
print(client.ping())
```

for the client code example as showed in homepage, how and when to close socket connection?

**Comment by collinmazb** [comment]
I think the correct way to use _make_client_ api is like this:

> with make_client(pingpong_thrift.PingPong, '127.0.0.1', 6000) as client:
>     print(client.ping())

Is that correct? In other way, we must ensure the connection be released at some point

**Comment by ethe** [comment]
`client.close()`, or using `with` syntax.

**Comment by ethe** [comment]
see https://github.com/Thriftpy/thriftpy2/blob/5b89e67518dea18eb952b0a3a76bba0a0c07cc17/examples/calculator/calc_client.py#L13

**Comment by collinmazb** [comment]
Got it, thanks
