### ISSUE TITLE
Parse error on empty set field value

### ISSUE THREAD

**Issue by danieljfarrell** [Thriftpy/thriftpy2#61]
The following thift file,

(**NB** that the file can be parsed correctly using the Thrift executable from https://thrift.apache.org/download,  tested with the latest version at the time of writing 0.12.0)

```thrift
struct Status {
	1: string state,
	2: optional set<string> info={},  # <-- problem line
}
	
service EchoService {
    string echo(1: string param),
    Status get_status(),
}
```

causes a parse error,
```python
Traceback (most recent call last):
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\thriftpy2\parser\parser.py", line 341, in p_simple_field
    val = _cast(p[3])(p[6])
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\porosity_env\lib\site-packages\thriftpy2\parser\parser.py", line 753, in __cast_set
    assert isinstance(v, (list, set))
AssertionError
```

The parse error is because Python does not have a literal for an empty set. The string `{}` in the thrift file is interpreted as a dict which generates the assertion error.

https://github.com/Thriftpy/thriftpy2/blob/cbc250d0d4473c20e9de08c3eea6cc44cf01c393/thriftpy2/parser/parser.py#L751

A potential fix is to check for empty dict values and force the return value to be a set:

```python
def _cast_set(t):
    assert t[0] == TType.SET

    def __cast_set(v):
        if len(v) == 0 and isinstance(v, dict):
            v = set()
        assert isinstance(v, (list, set))
        map(_cast(t[1]), v)
        if not isinstance(v, set):
            return set(v)
        return v
    return __cast_set
```

I'm working on a pull request and adding tests etc.

**Comment by ethe** [comment]
Thank you, The solution that you list above looks good to me.

**Comment by danieljfarrell** [comment]
I made the pull request. Test pass. Let me know what you think when you get the chance.

**Comment by danieljfarrell** [comment]
Excellent! Thanks! :smile:
