### ISSUE TITLE
Question about connecting to an Apache Thrift server with thrifpy2 client

### ISSUE THREAD

**Issue by danieljfarrell** [Thriftpy/thriftpy2#69]
I know that Apache Thrift does not work if the client and server are not same versions.

I would like to use thriftpy2 to connect to a Apache Thift sever (version 0.9.1), do you see any problems with this or is this within the scope of thriftpy2?

Thanks.

**Comment by ethe** [comment]
There is not any compatibility problems with Apache Thrift yet, and I think it would be support in design. If you find any problems using Thrifpy2 and Apache Thrift together, please post here, thank you.

**Comment by danieljfarrell** [comment]
I did make Thiftpy2 raise a protocol exception by cancelling a coroutine that was being awaited. The server was Apache Thirft the client was Thriftypy2. Don’t know if this is the reason. 

I will put together an example script and post here.

**Comment by ethe** [comment]
Check protocol's version mask, see https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/protocol/binary.py#L12

**Comment by jiffies** [comment]
> Check protocol's version, see https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/protocol/binary.py#L12
Ok,I tried it and It's compatible.

**Comment by ethe** [comment]
This exception would be raised when the socket was closed before receiving, and Thriftpy uses long connection as default. I can not ensure the reason until you give me more info about your case.

**Comment by jiffies** [comment]
> This exception would be raised when the socket was closed before receiving, and Thriftpy uses long connection as default. I can not ensure the reason until you give me more info about your case.
Thank you. I'll try more.By the way, do you know of any golang projects like thriftpy?

**Comment by ethe** [comment]
Sorry, I do not know. I doubt that Golang can do the same thing as Python, cause it does not have any ability of metaprogramming.

**Comment by ethe** [comment]
Closed in current
