### ISSUE TITLE
Follow Strict Data Type in TJsonProtocol

### ISSUE THREAD

**Issue by not94** [Thriftpy/thriftpy2#71]
Hey, I hava met a problem about using TJsonProtocol to serialize thrift obejct.

There is a double field defined in my thrift struct but assigned with a decimal object, which can not be serialized with TJsonProtocol.

I found the json_value function just return the value if it is a double field.

    def json_value(ttype, val, spec=None):
        if ttype in INTEGER or ttype in FLOAT or ttype == TType.STRING:
            return val
    
        if ttype == TType.BOOL:
            return True if val else False
    
        if ttype == TType.STRUCT:
            return struct_to_json(val)
    
        if ttype in (TType.SET, TType.LIST):
            return list_to_json(val, spec)
    
        if ttype == TType.MAP:
            return map_to_json(val, spec)

I know the easiest way is to change the decimal object to float object, but it is possible to follow the strict data type in json value? such as:

    def json_value(ttype, val, spec=None):
        if ttype in INTEGER:
    	   return int(val)

        if ttype in FLOAT:
    	   return float(val)

        if ttype == TType.STRING:
    	   return str(val)
    
        if ttype == TType.BOOL:
            return True if val else False
    
        if ttype == TType.STRUCT:
            return struct_to_json(val)
    
        if ttype in (TType.SET, TType.LIST):
            return list_to_json(val, spec)
    
        if ttype == TType.MAP:
            return map_to_json(val, spec)

Thanks a lot!

**Comment by ethe** [comment]
Hi,
I think the change you post above is fine.

**Comment by not94** [comment]
Thanks a lot ! Could I have a chance to make PR about this?

**Comment by ethe** [comment]
Welcome 😄
