### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by skylinetux** [Thriftpy/thriftpy2#74]
# pip install thriftpy2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting thriftpy2
  Using cached https://files.pythonhosted.org/packages/b1/6e/ee0400c5d25babf1426b20fc75192f723c693915e81d251056097206a161/thriftpy2-0.4.4.tar.gz
Requirement already satisfied: ply<4.0,>=3.4 in /usr/lib/python2.7/site-packages (from thriftpy2) (3.4)
Installing collected packages: thriftpy2
  Running setup.py install for thriftpy2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-68ikMM/thriftpy2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-68ikMM/thriftpy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sXHwhY/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-68ikMM/thriftpy2/
    Complete output (91 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/_compat.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/hook.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/http.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/rpc.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/server.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/thrift.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/tornado.py -> build/lib.linux-x86_64-2.7/thriftpy2
    copying thriftpy2/utils.py -> build/lib.linux-x86_64-2.7/thriftpy2
    creating build/lib.linux-x86_64-2.7/thriftpy2/contrib
    copying thriftpy2/contrib/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib
    creating build/lib.linux-x86_64-2.7/thriftpy2/parser
    copying thriftpy2/parser/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/parser
    copying thriftpy2/parser/exc.py -> build/lib.linux-x86_64-2.7/thriftpy2/parser
    copying thriftpy2/parser/lexer.py -> build/lib.linux-x86_64-2.7/thriftpy2/parser
    copying thriftpy2/parser/parser.py -> build/lib.linux-x86_64-2.7/thriftpy2/parser
    creating build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/binary.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/compact.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/exc.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/json.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    copying thriftpy2/protocol/multiplex.py -> build/lib.linux-x86_64-2.7/thriftpy2/protocol
    creating build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/_ssl.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/socket.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/sslsocket.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    creating build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/client.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/processor.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/rpc.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/server.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    copying thriftpy2/contrib/aio/socket.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio
    creating build/lib.linux-x86_64-2.7/thriftpy2/contrib/tracking
    copying thriftpy2/contrib/tracking/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/tracking
    copying thriftpy2/contrib/tracking/tracker.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/tracking
    creating build/lib.linux-x86_64-2.7/thriftpy2/transport/buffered
    copying thriftpy2/transport/buffered/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport/buffered
    creating build/lib.linux-x86_64-2.7/thriftpy2/transport/framed
    copying thriftpy2/transport/framed/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport/framed
    creating build/lib.linux-x86_64-2.7/thriftpy2/transport/memory
    copying thriftpy2/transport/memory/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/transport/memory
    creating build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/protocol
    copying thriftpy2/contrib/aio/protocol/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/protocol
    copying thriftpy2/contrib/aio/protocol/binary.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/protocol
    creating build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/transport
    copying thriftpy2/contrib/aio/transport/__init__.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/transport
    copying thriftpy2/contrib/aio/transport/buffered.py -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/aio/transport
    running egg_info
    writing requirements to thriftpy2.egg-info/requires.txt
    writing thriftpy2.egg-info/PKG-INFO
    writing top-level names to thriftpy2.egg-info/top_level.txt
    writing dependency_links to thriftpy2.egg-info/dependency_links.txt
    reading manifest file 'thriftpy2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'thriftpy2.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-2.7/thriftpy2/protocol/cybin
    copying thriftpy2/protocol/cybin/cybin.c -> build/lib.linux-x86_64-2.7/thriftpy2/protocol/cybin
    copying thriftpy2/protocol/cybin/cybin.pyx -> build/lib.linux-x86_64-2.7/thriftpy2/protocol/cybin
    copying thriftpy2/protocol/cybin/endian_port.h -> build/lib.linux-x86_64-2.7/thriftpy2/protocol/cybin
    copying thriftpy2/transport/cybase.c -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/cybase.pxd -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/transport/cybase.pyx -> build/lib.linux-x86_64-2.7/thriftpy2/transport
    copying thriftpy2/contrib/tracking/tracking.thrift -> build/lib.linux-x86_64-2.7/thriftpy2/contrib/tracking
    copying thriftpy2/transport/buffered/cybuffered.c -> build/lib.linux-x86_64-2.7/thriftpy2/transport/buffered
    copying thriftpy2/transport/buffered/cybuffered.pyx -> build/lib.linux-x86_64-2.7/thriftpy2/transport/buffered
    copying thriftpy2/transport/framed/cyframed.c -> build/lib.linux-x86_64-2.7/thriftpy2/transport/framed
    copying thriftpy2/transport/framed/cyframed.pyx -> build/lib.linux-x86_64-2.7/thriftpy2/transport/framed
    copying thriftpy2/transport/memory/cymemory.c -> build/lib.linux-x86_64-2.7/thriftpy2/transport/memory
    copying thriftpy2/transport/memory/cymemory.pyx -> build/lib.linux-x86_64-2.7/thriftpy2/transport/memory
    running build_ext
    building 'thriftpy2.transport.cybase' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/thriftpy2
    creating build/temp.linux-x86_64-2.7/thriftpy2/transport
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c thriftpy2/transport/cybase.c -o build/temp.linux-x86_64-2.7/thriftpy2/transport/cybase.o
    thriftpy2/transport/cybase.c:17:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-68ikMM/thriftpy2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-68ikMM/thriftpy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sXHwhY/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by skylinetux** [comment]
https://github.com/openzipkin/zipkin/tree/master/zipkin-lens/testdata

**Comment by aisk** [comment]
This is not a thriftpy2 related issue, and the error logs contains all information to resolve it, you can try to google it and you can save a lot of life now with learn to how to google.

I googled it for you for this time, and wish you learn how to use google. The anser is: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by ethe** [comment]
Please install `Python.h`

**Comment by ethe** [comment]
Closed temporary for more info.
