### ISSUE TITLE
Remote connection hbase error 

### ISSUE THREAD

**Issue by chaojiwudishuai** [Thriftpy/thriftpy2#79]
thriftpy2.thrift.TApplicationException: <exception str() failed>

**Comment by ethe** [comment]
Could you please tell me how I can reproduce it?

**Comment by chaojiwudishuai** [comment]
import happybase

connection = happybase.Connection('114.116.49.76')
print(connection.tables())

**Comment by chaojiwudishuai** [comment]
我用happybase 连接华为云上的mapreduce集群时报的错

**Comment by chaojiwudishuai** [comment]
> Could you please tell me how I can reproduce it?
我用happybase 连接华为云上的mapreduce集群hbase时报的错

测试代码：
import happybase

connection = happybase.Connection('114.116.49.76')
print(connection.tables())

**Comment by ethe** [comment]
I can not reproduce it, maybe you should ask for help from happybase contributors.

**Comment by ethe** [comment]
Closed for current, may open for more info.

**Comment by chenhjcs** [comment]
check your thrift server version, happyhbase don't support thrift2
