### ISSUE TITLE
is it support THttpClient?

### ISSUE THREAD

**Issue by naah69** [Thriftpy/thriftpy2#82]
is it support THttpClient?

**Comment by ethe** [comment]
Yes it is.

**Comment by naah69** [comment]
but when i try using it to send to hbase.it raise exception

**Comment by naah69** [comment]
and how to add header in `thriftpy2.http.make_client`

**Comment by ethe** [comment]
The protocol may be not compatible with HBase I think, but I need more info to ensure that.
